# This is a basic workflow to help you get started with Actions

name: Build-Desktop-Release

on:
  #  push:
  #    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag-name:
        description: "Release Tag Name"
        required: true
      git-ref:
        description: "Release Git Ref"
        required: true
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: ZIP file
        run: zip README-macos.zip README.md

      - name: Change zip name
        run: mv README-macos.zip README-x86-macos.zip

      - name: Cache Linux AppImage (x32) release
        uses: actions/upload-artifact@v1
        with:
          name: README-x86-macos.zip
          path: ./README-x86-macos.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: List file
        run: ls -rl

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - uses: DeLaGuardo/setup-clojure@master
        with:
          # To use Clojure CLI 1.10.1.561 based on tools.deps
          cli: '1.10.1.469'

      - run: Dir .


  release:
    needs: [build-macos, build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download the Debian asset
        uses: actions/download-artifact@v1
        with:
          name: README-x86-macos.zip
          path: ./

      - name: List file
        run: ls -rl

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag-name }}
          release_name: TEST CI (DON'T DOWNLOAD) ${{ github.event.inputs.tag-name }}
          draft: true
          prerelease: true

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./README-x86-macos.zip
          asset_name: README-macos.zip
          asset_content_type: application/zip